# Generated by Django 4.0.4 on 2022-05-01 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_actions_taken', models.TextField()),
                ('error_message', models.CharField(max_length=255)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.siteactionstaken')),
            ],
        ),
    ]
